CFLAGS=-W -Wall -Wextra -lm -fopenmp
all:
	$(CC) $(CFLAGS) ans_2opt_omp1.c -o ans_2opt_omp1
	$(CC) $(CFLAGS) ans_2opt_omp2.c -o ans_2opt_omp2
	$(CC) $(CFLAGS) ans_2opt_omp3.c -o ans_2opt_omp3 
	$(CC) $(CFLAGS) ans_2opt_omp21.c -o ans_2opt_omp21
