C=gcc
CFLAGS=-W -Wall -Wextra
all:
#	$(CC) $(CFLAGS) ans_2opt_s.c -o ans_2opt_s -lm -lpthread
#	$(CC) $(CFLAGS) ans_2opt_p1.c -o ans_2opt_p1 -lm -lpthread
#	$(CC) $(CFLAGS) ans_2opt_p2.c -o ans_2opt_p2 -lm -lpthread
#	$(CC) $(CFLAGS) ans_2opt_sp.c -o ans_2opt_sp -lm -lpthread
#	$(CC) $(CFLAGS) ans_2opt_sp2.c -o ans_2opt_sp2 -lm -lpthread
#	$(CC) $(CFLAGS) ans_2opt_s_timed.c -o ans_2opt_s_timed -lm -lpthread
	$(CC) $(CFLAGS) ans_2opt_sp3.c -o ans_2opt_sp3 -lm -lpthread
#	$(CC) $(CFLAGS) ans_2opt_sp4.c -o ans_2opt_sp4 -lm -lpthread
	$(CC) $(CFLAGS) ans_2opt_sp5.c -o ans_2opt_sp5 -lm -lpthread
#	$(CC) $(CFLAGS) ans_2opt_sp6.c -o ans_2opt_sp6 -lm -lpthread
	$(CC) $(CFLAGS) ans_2opt_sp7.c -o ans_2opt_sp7 -lm -lpthread
	$(CC) $(CFLAGS) ans_2opt_sp9.c -o ans_2opt_sp9 -lm -lpthread
	




clean:
	rm -f ans_2opt

